account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name="accounts"

urlpatterns = [
    path('login/',
            auth_views.LoginView.as_view(
                template_name='account/login.html'),
            name='login'
    ),
    path('logout/',
            auth_views.LogoutView.as_view(
            template_name='account/logout.html'),
        name='logout'
    ),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('user_list/', views.user_list, name='user_list'),
    path('<str:username>', views.profile, name='profile'),
    path('password-change/', 
            auth_views.PasswordChangeView.as_view(
                template_name='account/password_change.html'), 
            name='password_change'),
    path('password-change-done/', 
            auth_views.PasswordChangeView.as_view(
                template_name='account/password_change_done.html'), 
            name='password_change_done'),

    path(
        'follow/<str:username>',
        views.follow,
        name='follow'
    ),
    path(
        'unfollow/<str:username>',
        views.unfollow,
        name='unfollow'
    )
]

image/urls.py
from django.urls import path
from . import views

app_name='images'
urlpatterns = [
    path('upload/',
            views.image_upload,
            name='image_upload'
    ),
    path('list/',
        views.image_list,
        name='image_list'
    ),
    path(
        '<int:id>/<str:slug>/',
        views.image_detail,
        name='image_detail'
    ),
    path(
        'like/<int:id>',
        views.image_detail,
        name='image_like'
    ),
    path(
        'unlike/<int:id>',
        views.image_detail,
        name='image_unlike'
    ),
]

weshare/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

from .settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path(
        'social-auth/',
        include('social_django.urls', namespace='social')),
    path('image/', include('image.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

account/models.py
from hashlib import md5

from django.db import models
from django.contrib.auth.models import User


class Contact(models.Model):

    user_from = models.ForeignKey(
        to=User,
        related_name='from_set',
        on_delete=models.CASCADE)
    user_to = models.ForeignKey(
        to=User,
        related_name='to_set',
        on_delete=models.CASCADE)
    created = models.DateTimeField(
        auto_now_add=True,
        db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(
            self.user_from, self.user_to)


# Add following field to User dynamically
User.add_to_class(
    'following',
    models.ManyToManyField(
        'self',
        through=Contact,
        related_name='followers',
        symmetrical=False)
)

def gravatar(self, size=80):
    md5_digest = md5(self.email.lower().encode('utf-8')).hexdigest()
    return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(md5_digest, size)


User.add_to_class(
    'gravatar',
    gravatar
)

image/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse

class Image(models.Model):

    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='images_created'
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)

    image = models.ImageField(upload_to='images/%Y/%m/%d/')

    user_like = models.ManyToManyField(
            to=User,
            related_name='image_liked',
            blank=True
    )
    
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:image_detail', args=[self.id, self.slug])

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class MyUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

image/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('title', 'description', 'image')

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User 

from .forms import MyUserCreationForm
from .models import Contact

@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html')

def register(request):
    if request.method == 'POST':
        user_form = MyUserCreationForm(request.POST)
        if user_form.is_valid():
            new_user =  user_form.save(commit=False)
            new_user.set_password(
                    user_form.cleaned_data['password1']
            )
            new_user.save()

            return render(request,
                'account/register_done.html',
                {'new_user': new_user})
    else:
        user_form = MyUserCreationForm()
    return render(request,
            'account/register.html',
            {'user_form': user_form})


@login_required
def profile(request, username):
    user = User.objects.filter(username=username).first()
    return render(request,
            'account/profile.html',
            {'user':user}
    )

@login_required
def user_list(request):
    user_list = User.objects.all()

    return render(
            request,
            'account/user_list.html',
            {'user_list':user_list}
    )

@login_required
def follow(request, username):
    user_to = User.objects.filter(username=username).first()
    user_from = request.user
    con = Contact(
        user_from=user_from,
        user_to=user_to
    )
    con.save()
    return redirect('accounts:profile', username=username)


@login_required
def unfollow(request, username):
    user_to = User.objects.filter(username=username).first()
    user_from = request.user
    con = Contact.objects.filter(user_from=user_from, user_to=user_to).first()
    if con:
        con.delete()
    return redirect('accounts:profile', username=username)

image/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import ImageForm
from .models import Image

import pdb


@login_required
def image_upload(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            image_new = form.save(commit=False)
            image_new.user = request.user
            image_new.save()
            return render(request, 'image/image_upload_done.html')
    else:
        form = ImageForm()
    return render(request, 'image/image_upload.html', { 
        'form':form
    })


@login_required
def image_list(request):
    image_list = Image.objects.all()
    paginator = Paginator(image_list, 3)
    page = request.GET.get('page')

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        images = paginator.page(paginator.num_pages)

    return render(
           request,
           'image/image_list.html',
           {'images':images}
    ) 

@login_required
def image_detail(request, id, slug):
    image = Image.objects.filter(id=id, slug=slug).first()
    
    return render(
            request,
            'image/image_detail.html',
            {'image':image}
    )

@login_required
def image_like(request, id):
    image = Image.objects.get(id=id)
    image.user_like.add(request.user)
    return redirect('images:image_detail', id=image.id, slug=image.slug)

@login_required
def image_unlike(request, id):
    image = Image.objects.get(id=id)
    image.user_like.remove(request.user)
    return redirect('images:image_detail', id=image.id, slug=image.slug)
    #return redirect('images:image_detail',args={'id': id, 'slug':image.slug})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>
<body>
  <div id="header">
    <span class="logo">WeShare</span>
    {% if request.user.is_authenticated %}
      <ul class="menu">
        <li>
          <a href="{% url "accounts:dashboard" %}">My dashboard</a>
        </li>
        <li>
          <a href="{% url "images:image_list" %}">Images</a>
        </li>
        <li>
          <a href="{% url "accounts:user_list" %}">Users</a>
        </li>
      </ul>
    {% endif %}
    <span class="user">
      {% if request.user.is_authenticated %}
        Hello  <a href="{% url "accounts:profile" request.user.username %}"><u>{{ request.user.first_name }}</u>,</a>
        <a href="{% url "accounts:logout" %}"><u>Logout</u></a>
        /<a href="{% url "accounts:password_change" %}"><u>Change Password</u></a>
      {% else %}
        <a href="{% url "accounts:login" %}"><u>Log-in</u></a>
      {% endif %}
    </span>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
</body>
</html>

account/templates/up_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>
<body>
  <div id="header">
    <span class="logo">WeShare</span>
    <span class="user">
    {% if request.user.is_authenticated %}
      Hello {{ request.user.first_name}}
          <a href="{% url "logout" %}">Logout</a>
          <a href="{% url "password_change" %}">change password</a>
    {% else %}
          <a href="{% url "login" %}">LOG-IN</a>
    {% endif %}
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

image/templates/image/image_detail.html
{% extends 'base.html' %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}

<h1>{{ image.title }}</h1>
<img src="{{ image.image.url }}" class="image-detail">

{% with total_likes=image.user_like.count users_like=image.user_like.all %}
<div class="image-info">
  <div>
      {% if request.user in users_like %}
        <a class="count-like" href="{% url "images:image_unlike" image.id %}">
            {% if total_likes %}
                {{ total_likes }}
                like{{ total_likes|pluralize }}
             {% else %}
                {{ total_likes }}
                like
             {% endif %}
        </a>
     {% else %}
        <a class="count" href="{% url "images:image_like" image.id %}">
            {% if total_likes %}
                {{ total_likes }}
                like{{ total_likes|pluralize }}
            {% else %}
                {{ total_likes }}
                like
            {% endif %}
        </a>
    {% endif %}
  </div>
  {{ image.description|linebreaks }}
</div>
{% endwith %}

{% endblock %}

image/templates/image/image_list.html
{% extends 'base.html' %}

{% block title %}image{% endblock %}

{% block content %}
{% load thumbnail %}

<h1>Image</h1>

<p>If you want to upload new image, please click <a href="{% url "images:image_upload" %}">here</a></p>


<div id="image-list">

    {% for image in images %}
    <div class="image">
      <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image "300x300" crop="100%" as im %}
          <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}">
            {{ im.url }}
          </a>
        {% endthumbnail %}
      </a>
      <div class="info">
        <a href="{{ image.get_absolute_url }}" class="title">
          {{ image.title }}
          </a> </div>
    </div>
  {% endfor %}
</div>

<div>
    <ul>
      {% if images.has_previous %}
        <li>
          <a href="?page={{ images.previous_page_number }}"> &larr; Newer images</a>
        </li>
      {% endif %}
      {% if images.has_next %}
        <li>
          <a href="?page={{ images.next_page_number }}">Older images &rarr;</a>
        </li>
      {% endif %}    
    </ul>
  </div>

{% endblock %}

image/templates/image/image_upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
{% endblock %}

image/templates/image/image_upload_done.html
{% extends 'base.html' %}

{% block content %}
<p>Image uploaded successfully!</p>
{% endblock %}